Download, compile, and cache cmake
The source code is currently downloaded from the official sources. It might be nice at some point to instead host a pre-build version on AWS S3 or something.

Upon downloading, cmake is compiled. This takes a long time, but it only hast to happen once for a project. At the moment, all the cmake stuff is put in with the Python stuff. Maybe later there can be a directory just for cmake, but this way everything is already on the $PATH, and the default cache saving/loading logic just works. The path is `.heroku/Python`, and cmake will put things in `.heroku/Python/bin`, and create `.heroku/Python/Modules`.

Later releases of the app will load the cached version, which simply looks for the existence of the cmake binary, similar to how the buildpack finds the cached Python install, for example.

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -192,8 +192,8 @@ if [ "$FRESH_PYTHON" ] || [[ ! $(pip --version) == *$PIP_VERSION* ]]; then
     cd $ROOT_DIR/vendor/pip-$PIP_VERSION/
     python setup.py install &> /dev/null
     cd $WORKING_DIR
-
   bpwatch stop install_pip
+
   bpwatch stop prepare_environment
 fi
 
@@ -212,6 +212,38 @@ if (grep -Fiq "hg+" requirements.txt) then
     /app/.heroku/python/bin/pip install  mercurial | cleanup | indent
   bpwatch stop mercurial_install
 fi
+
+
+CMAKE_VERSION="2.8.6"
+CMAKE_FOLDER=cmake-$CMAKE_VERSION
+CMAKE_PREFIX=`pwd`/.heroku/python  # just use that...
+
+# Install cmake because the world sucks
+if [ ! -f .heroku/python/bin/cmake ]; then
+  bpwatch start install_cmake
+
+    puts-warn "Installing cmake ($CMAKE_VERSION)"
+    curl http://www.cmake.org/files/v2.8/cmake-2.8.6.tar.gz -s | tar zx &> /dev/null
+    if [[ $? != 0 ]] ; then
+      puts-warn "Requested cmake ($CMAKE_VERSION) was not found."
+      puts-warn "Aborting.  :("
+      exit 1
+    fi
+
+    cd $CMAKE_FOLDER
+      ./bootstrap --prefix=$CMAKE_PREFIX | indent
+      make | indent
+    cd ../
+
+    mv $CMAKE_FOLDER/bin/* .heroku/python/bin/
+    if [ ! -d .heroku/python/Modules ]; then
+      mv $CMAKE_FOLDER/Modules .heroku/python/
+    fi
+    rm -r $CMAKE_FOLDER
+
+  bpwatch stop install_cmake
+fi
+
 
 # Install dependencies with Pip.
 puts-step "Installing dependencies using Pip ($PIP_VERSION)"
